import pandas as pd
from sklearn.metrics import (accuracy_score, classification_report,
                             confusion_matrix, f1_score)
import torch

def predict(model:torch.nn.Module, dataloader:torch.utils.data.DataLoader, device:torch.device):
    """
    Runs the test loop and returns all true labels, predicted labels, and confidence scores.

    Parameters
    ----------
    model: torch.nn.Module
        A trained ResNet-18 model.

    dataloader: torch.utils.data.DataLoader
        A DataLoader object containing the testing data.

    device: torch.device
        A torch.device object representing the device on which the model is to be tested on.

    Returns
    -------
    tuple: a tuple containing:
        y_true (list): a list containing the true classes for each prediction.
        y_pred (list): a list containing the predicted classes for each prediction.
        confidence (list): a list containing the confidence scores for each prediction.
    """
    y_true = []
    y_pred = []
    all_confidence = []

    model.eval()
    with torch.no_grad():
        for X, y in dataloader:
            X = X.to(device, non_blocking=True)
            y = y.to(device, non_blocking=True)

            logits = model(X)
            prob = torch.softmax(logits, dim=1)
            confidence, preds = prob.max(dim=1)

            y_true.extend(y.cpu().numpy())
            y_pred.extend(preds.cpu().numpy())
            all_confidence.extend(confidence.cpu().numpy())

    return y_true, y_pred, all_confidence

def compute_metrics(y_true:list, y_pred:list, class_names:dict, report_f1: bool = False):
    """
    Computes all important metrics (such as per-class precision, per-class recall, confusion matrices, accuracy scores,
    macro F1-score, and weighted F1-score) needed for our analysis.

    Parameters
    ----------
    y_true: list
        A list containing the true classes for each prediction.

    y_pred: list
        A list containing the predicted classes for each prediction.

    class_names: dict
        A dictionary mapping integer class IDs to class names.

    report_f1: bool
        If True, the method will report the macro and weighted F1-scores independently of the classification report.
        Although both values can be found in the report, this parameter makes them easier to access and use through
        the rest of the project.

    Returns
    -------
    tuple: a tuple containing:
        report (dict): A dictionary generated by sklearn.metrics.classification_report. This report contains the
            precision, recall, F1-score, support, macro average, and weighted average for each class.

        confusion_matrices (dict): A dict containing the confusion matrices for each class. In total, there are three
            matrices returned: The unnormalized matrix, row normalized matrix, and column normalized matrix.

        class_confusion (pd.DataFrame): A DataFrame containing the class-by-class confusion.

        accuracy (float): A float representing the accuracy of the predictions. This metric is calculated with
        sklearn.metrics.accuracy_score.

        macro_f1 (float): If return_f1 is True, the macro F1-Score will be returned.

        weight_f1 (float): if return_f1 is True, the weighted F1-Score will be returned.

    """
    # Creating an order sequence of class names
    class_names = [class_names[i] for i in range(len(class_names))]

    report = classification_report(y_true, y_pred, target_names=class_names, output_dict=True)

    raw_cm = confusion_matrix(y_true, y_pred)
    row_cm = confusion_matrix(y_true, y_pred, normalize='true')
    column_cm = confusion_matrix(y_true, y_pred, normalize='pred')

    confusion_matrices = {'raw': raw_cm, 'row': row_cm, 'column': column_cm}

    data = []

    for i, class_name in enumerate(class_names):
        for j, pred_name in enumerate(class_names):
            if i != j:
                data.append({'class': class_name, 'pred': pred_name, 'error': row_cm[i, j]})

    class_confusion = pd.DataFrame(data=data)
    class_confusion["Count"] = [raw_cm[i, j] for i in range(len(class_names))
                                for j in range(len(class_names)) if i != j]
    class_confusion.sort_values(by='Count', ascending=False, inplace=True, ignore_index=True)

    accuracy = accuracy_score(y_true, y_pred)

    if report_f1:
        macro_f1 = f1_score(y_true, y_pred, average='macro')
        weighted_f1 = f1_score(y_true, y_pred, average='weighted')
        return report, confusion_matrices, class_confusion, accuracy, macro_f1, weighted_f1

    return report, confusion_matrices, class_confusion, accuracy

